spring.application.name=consumer
server.port=8444

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ecommercedb
producer.service.url=https://localhost:8443/products

client.ssl.key-store=classpath:client-keystore.p12
client.ssl.key-store-password=pass1234
client.ssl.trust-store=classpath:client-truststore.p12
client.ssl.trust-store-password=pass1234

consumer.private.key.path=keys/consumer_private.key
consumer.public.key.path=keys/consumer_public.key
producer.public.key.path=keys/producer_public.key